config/routes.rb
Indigestion::Application.routes.draw do

  root to: 'curators#index'

  devise_for :curators

  resources :curators, only: [:index, :show] do
    scope do
      resources :links, only: :index
    end
    resources :followers, only: [:create, :index]
    resources :followings, only: [:index]
  end

  resource :search, only: :show, controller: :search

  resources :links, only: [:new, :create]
  resources :followings, only: :destroy

end

app/models/concerns/with_followers_notification.rb
module WithFollowersNotification
  def notify_followers_of(link)
    followers.each do |follower|
      CuratorMailer.curated_link_created(link, follower).deliver
    end
  end
end

app/models/curator.rb
class Curator < ActiveRecord::Base
  include WithFollowersNotification
  extend FriendlyId

  has_many :links

  validates_presence_of :username, :email

  friendly_id :username, use: :slugged

  acts_as_followable
  acts_as_follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  alias following_follows follows_scoped
  alias follower_follows followers_scoped

  def recent_links
    links.order('id desc')
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:title, :description]

  belongs_to :curator

  validates_presence_of :url, :title, :curator

  after_create :notify_followers

  private

  def notify_followers
    curator.notify_followers_of(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include WithCurrentCurator

  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  helper_method :current_curator_following?
  helper_method :current_curator_is?

  protected

  def configure_permitted_parameters
    [:sign_in, :sign_up, :account_update].each do |it|
      devise_parameter_sanitizer.for(it) {
          |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me)
      }
    end
  end
end

app/controllers/concerns/with_curator.rb
module WithCurator
  def set_curator
    @curator = Curator.friendly.find(params[:curator_id] || params[:id])
  end
end

app/controllers/concerns/with_current_curator.rb
module WithCurrentCurator
  def current_curator_following?(curator)
    curator_signed_in? && current_curator.following?(curator)
  end

  def current_curator_is?(curator)
    curator_signed_in? && current_curator == curator
  end
end

app/controllers/curators_controller.rb
class CuratorsController < ApplicationController
  include WithCurator

  before_action :set_curator, only: [:show]

  def show
    @links = @curator.recent_links.limit(5)
    @followings = @curator.following_follows
    @followers = @curator.follower_follows
  end

  def index
    @curators = Curator.all
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  include WithCurator

  before_action :authenticate_curator!, only: :create
  before_action :set_curator

  def create
    current_curator.follow(@curator)
    flash[:notice] = 'Followed successfully'
    redirect_to :back
  end

  def index
    @follows = @curator.follower_follows.page(params[:page]).per(5)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  include WithCurator

  before_action :authenticate_curator!, only: :destroy
  before_action :set_curator

  def destroy
    current_curator.stop_following(@curator)
    flash[:notice] = 'Unfollowed successfully'
    redirect_to :back
  end

  def index
    @follows = @curator.following_follows.page(params[:page]).per(5)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  include WithCurator

  before_action :set_curator, only: :index
  before_action :set_current_curator, only: [:create, :new]
  before_action :authenticate_curator!, only: [:create, :new]

  def index
    @links = @curator.recent_links.page(params[:page]).per(25)
  end

  def create
    @link = Link.create params.require(:link).permit(:title, :url, :description).merge(curator: @curator)
    if @link.errors.any?
      flash[:alert] = "Link creation failed: #{@link.errors.first}"
      redirect_to action: :new
    else
      flash[:notice] = 'Link created successfully'
      redirect_to curator_path(@curator)
    end
  end

  def new
    @link = Link.new
  end

  private

  def set_current_curator
    @curator = current_curator
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def show
    @searches = PgSearch.multisearch(params.require(:query)).page(params[:page]).per(25)
    @links = @searches.map(&:searchable)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def curator_digest_title(curator)
    "#{curator.username}'s Digest"
  end

  def curator_followers_title(curator)
    "#{curator.username}'s Followers"
  end

  def curator_followings_title(curator)
    "#{curator.username}'s Followings"
  end
end

app/views/curators/_curator.html.erb
<div style="float: left; margin: 4px">
  <a href="<%= curator_path(curator) %>"><%= curator.username %></a>
</div>

app/views/curators/_curator_heading.html.erb
<div class="page-header">
  <div class="row">
    <div class="col-md-11">
      <h1><%= yield :curator_heading %></h1>
    </div>
    <ul class="col-md-1 h1">
      <%= render 'curators/follow_buttons', curator: @curator %>
    </ul>
  </div>
</div>

app/views/curators/_follow_buttons.html.erb
<% unless current_curator_is?(curator) %>
    <% if current_curator_following?(curator) %>
        <%= form_tag following_path(curator), method: :delete do %>
            <%= submit_tag 'Unfollow', class: 'btn btn-warning' %>
        <% end %>
    <% else %>
        <%= form_tag curator_followers_path(curator), method: :post do %>
            <%= submit_tag 'Follow', class: 'btn btn-primary' %>
        <% end %>
    <% end %>
<% end %>

app/views/curators/index.html.erb
<div class="page-header">
  <h1>Curators</h1>
</div>


<div class="row">
  <div class="col-md-12">
    <%= render @curators %>
  </div>
</div>

app/views/curators/show.html.erb
<%= content_for :curator_heading do %>
    <%= @curator.username %>'s Page
<% end %>
<%= render 'curator_heading' %>

<div class="row">
  <div class="col-md-7">
    <h2><a href="<%= curator_links_path(@curator) %>"><%= curator_digest_title(@curator) %></a></h2>
    <%= render partial: 'links/link', collection: @links, as: :link %>
    <a href="<%= curator_links_path(@curator) %>">More...</a>
  </div>
  <div class="col-md-5">
    <div class="row ">
      <div class="col-md-12">
        <h3><a href="<%= curator_followers_path(@curator) %>"><%= curator_followers_title(@curator) %></a></h3>
        <%= render partial: 'followers/follower', collection: @followers, as: :follow %>
      </div>
    </div>
    <div class="row ">
      <div class="col-md-12">
        <h3><a href="<%= curator_followings_path(@curator) %>"><%= curator_followings_title(@curator) %></a></h3>
        <%= render partial: 'followings/following', collection: @followings, as: :follow %>
      </div>
    </div>
  </div>
</div>

app/views/followers/_follower.html.erb
<ul>
  <span class="glyphicon glyphicon-arrow-left"></span>
  <a href="<%= curator_path(follow.follower) %>"><%= follow.follower.username %></a>
</ul>

app/views/followers/index.html.erb
<%= content_for :curator_heading do %>
    <%= @curator.username %>'s Followers
<% end %>
<%= render 'curators/curator_heading' %>

<%= render partial: 'follower', collection: @follows, as: :follow || 'There are no followers yet' %>

<div class="row">
  <div class="col-md-12">
    <%= paginate @follows %>
  </div>
</div>

app/views/followings/_following.html.erb
<ul>
  <span class="glyphicon glyphicon-arrow-right"></span>
  <a href="<%= curator_path(follow.followable) %>"><%= follow.followable.username %></a>
</ul>

app/views/followings/index.html.erb
<%= content_for :curator_heading do %>
    <%= @curator.username %>'s Followings
<% end %>

<%= render 'curators/curator_heading' %>
<%= render partial: 'following', collection: @follows, as: :follow || 'There are no followings yet' %>

<div class="row">
  <div class="col-md-12">
    <%= paginate @follows %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Indigestion</title>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <%= stylesheet_link_tag 'application' %>
</head>
<body>


<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">Indigestion</a>
    </div>

    <ul class="nav navbar-nav">
      <% if curator_signed_in? %>
          <li><%= link_to('Sign out', destroy_curator_session_path) %></li>
      <% else %>
          <li><%= link_to('Sign up', new_curator_registration_path) %></li>
          <li><%= link_to('Sign in', new_curator_session_path) %></li>
      <% end %>
    </ul>

    <form class="navbar-form navbar-left" action="<%= search_path  %>" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search in Indigestion" name="query">
      </div>
      <button type="submit" class="btn btn-default">
        <span class="glyphicon glyphicon-search"></span>
      </button>
    </form>


    <div class="navbar-form">
        <a href="<%=new_link_path %>" class="btn btn-success navbar-right" title="Add Link">
          <span class="glyphicon glyphicon-plus"></span>
        </a>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
    <% elsif alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
    <% end %>
  </div>

  <%= yield %>
  <div class="row">
    <div class="col-md-12">
      <footer>
        <hr>
        <p>&copy; Copyright 2014 Indigestion</p>
      </footer>
    </div>
  </div>
</div>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/links/_link.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>
      <span class="glyphicon glyphicon-link"></span><a href="<%= link.url %>">
      <%= link.title %>
    </a>
      <small><%= link.created_at.strftime('%Y-%m-%d') %></small>
    </h3>
    <p>
      <%= link.description %>
    </p>
  </div>
</div>
<hr>

app/views/links/index.html.erb
<%= content_for :curator_heading do %>
    <a href="<%= curator_path(@curator) %>"><%= curator_digest_title(@curator) %></a>
<% end %>

<%= render 'curators/curator_heading' %>
<%= render @links || 'There are no links yet' %>

<div class="row">
  <div class="col-md-12">
    <%= paginate @links %>
  </div>
</div>

app/views/links/new.html.erb
<div class="page-header">
  <h1>Create Link</h1>
</div>


<%= form_for(@link, html: {class: 'form-horizontal', role: 'form'}) do |f| %>

    <div class="form-group">
      <label for="title" class="col-md-2 control-label">Title</label>

      <div class="col-md-10">
        <%= f.text_field :title, class: 'form-control', placeholder: 'An Awesome Link' %>
      </div>
    </div>


    <div class="form-group">
      <label for="url" class="col-md-2 control-label">Url</label>

      <div class="col-md-10">
        <%= f.url_field :url, class: 'form-control', placeholder: 'http://awesome.com' %>
      </div>
    </div>

    <div class="form-group">
      <label for="description" class="col-md-2 control-label">Description</label>

      <div class="col-md-10">
        <%= f.text_area :description, class: 'form-control', placeholder: 'This link is awsome' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Cancel', :back, class: 'btn' %>
      </div>
    </div>
<% end %>

app/views/search/show.html.erb
<%= render partial: 'links/link', collection: @links %>


<div class="row">
  <div class="col-md-12">
    <%= paginate @searches %>
  </div>
</div>